FROM mcr.microsoft.com/devcontainers/cpp:1-ubuntu-22.04

RUN apt update && \
        apt-get install --no-install-recommends -y\
        mesa-utils libglu1-mesa-dev freeglut3-dev mesa-common-dev \
        lib3ds-dev libsdl2-image-dev libdevil-dev